### ISSUE TITLE
GetPricePerLiter gibt immer 0 zurück

### ISSUE THREAD

**Issue by BrunnerLivio** [OddisJungs/PetrolStation#1]
In **Fuel.cs**
`public int GetPricePerLiter()
            {
                return 0;
            }`

Good Game 
Well Played

**Comment by Reto411** [comment]
Ich weis :)
De rest isch au shitty, egal welche branch du studiers (bsunders the vom Roger)

**Comment by BrunnerLivio** [comment]
oh ihr hend ja huere viel branches für so wenig users hahahaha

**Comment by Reto411** [comment]
es gaht nüd über branches
Je meh desto besser

**Comment by Reto411** [comment]
Wie dönt ihr üchi klasse initialisiere, dönder das id businesslogik oder id test case oder sust a arsch vo de welt?

**Comment by BrunnerLivio** [comment]
I de TestCases. Chasch ja nacheluege, üsi Tankstell isch au online. Da gfindsch swichtigste : https://github.com/BrunnerLivio/Tankstelle-M226/blob/master/GasStation.Test/GasStationTest.cs

Die Testfäll gönd nachem Dokument wo de Odi üs letschtmal ufs share da hend. Isch a ufem Google Drive
